# MTA Subway Line Groupings

## Goal:
- Group the subway stations into their respective train lines:

In [82]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

stations = pd.read_csv('../cleaned_data/MTA_Subway_Stations_With_Census_Tracts_2025.csv', low_memory=False)

stations.shape

(496, 9)

In [83]:
stations[stations['Daytime Routes'].str.contains('J', na=False)]

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
79,J Z,J12,80,121 St,Q,40.700492,-73.828294,144.00,144
80,J,J13,81,111 St,Q,40.697418,-73.836345,124.00,124
81,J Z,J14,82,104 St,Q,40.695178,-73.844330,26.00,26
82,J Z,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20
83,J,J16,84,85 St-Forest Pkwy,Q,40.692435,-73.860010,12.00,12
84,J Z,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4
85,J,J19,86,Cypress Hills,Bk,40.689941,-73.872550,1182.01,1182
86,J Z,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178
87,J Z,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174
88,J,J22,89,Cleveland St,Bk,40.679947,-73.884639,1168.00,1168
89,J Z,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198
90,J Z,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198
91,J Z,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405
92,J Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369
93,J,J29,94,Halsey St,Bk,40.686370,-73.916559,397.00,397
94,J Z,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397
95,J,J31,96,Kosciuszko St,Bk,40.693342,-73.928814,289.00,289
96,M J Z,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287
97,M J,M12,98,Flushing Av,Bk,40.700260,-73.941126,285.01,285
98,M J,M13,99,Lorimer St,Bk,40.703869,-73.947408,491.00,491
99,M J,M14,100,Hewes St,Bk,40.706870,-73.953431,529.00,529
100,M J Z,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529
101,M J Z,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18
102,J Z,M19,103,Bowery,M,40.720280,-73.993915,18.00,18
103,J Z,M20,104,Canal St,M,40.718092,-73.999892,41.00,41
104,J Z,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29
105,J Z,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15
106,J Z,M23,107,Broad St,M,40.706476,-74.011056,7.00,7
278,E J Z,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246
279,E J Z,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208

In [84]:
stations[stations['Daytime Routes'].str.contains('Z', na=False)]

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
79,J Z,J12,80,121 St,Q,40.700492,-73.828294,144.00,144
81,J Z,J14,82,104 St,Q,40.695178,-73.844330,26.00,26
82,J Z,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20
84,J Z,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4
86,J Z,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178
87,J Z,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174
89,J Z,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198
90,J Z,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198
91,J Z,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405
92,J Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369
94,J Z,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397
96,M J Z,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287
100,M J Z,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529
101,M J Z,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18
102,J Z,M19,103,Bowery,M,40.720280,-73.993915,18.00,18
103,J Z,M20,104,Canal St,M,40.718092,-73.999892,41.00,41
104,J Z,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29
105,J Z,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15
106,J Z,M23,107,Broad St,M,40.706476,-74.011056,7.00,7
278,E J Z,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246
279,E J Z,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208

# Note:
- Z always appears with J (it is the express train w.r.t. the J train)

In [85]:
# Split rows into multiple rows based on 'Daytime Routes' column
stations_expanded = stations.assign(**{
    'Daytime Routes': stations['Daytime Routes'].str.split(' ')
}).explode('Daytime Routes')
stations_expanded.head()

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
0,N,R01,1,Astoria-Ditmars Blvd,Q,40.775036,-73.912034,115.0,115
0,W,R01,1,Astoria-Ditmars Blvd,Q,40.775036,-73.912034,115.0,115
1,N,R03,2,Astoria Blvd,Q,40.770258,-73.917843,125.0,125
1,W,R03,2,Astoria Blvd,Q,40.770258,-73.917843,125.0,125
2,N,R04,3,30 Av,Q,40.766779,-73.921479,63.0,63

In [86]:
stations_expanded.shape

(767, 9)

In [87]:
stations_expanded[stations_expanded['Daytime Routes'] == 'J']

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
79,J,J12,80,121 St,Q,40.700492,-73.828294,144.00,144
80,J,J13,81,111 St,Q,40.697418,-73.836345,124.00,124
81,J,J14,82,104 St,Q,40.695178,-73.844330,26.00,26
82,J,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20
83,J,J16,84,85 St-Forest Pkwy,Q,40.692435,-73.860010,12.00,12
84,J,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4
85,J,J19,86,Cypress Hills,Bk,40.689941,-73.872550,1182.01,1182
86,J,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178
87,J,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174
88,J,J22,89,Cleveland St,Bk,40.679947,-73.884639,1168.00,1168
89,J,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198
90,J,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198
91,J,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405
92,J,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369
93,J,J29,94,Halsey St,Bk,40.686370,-73.916559,397.00,397
94,J,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397
95,J,J31,96,Kosciuszko St,Bk,40.693342,-73.928814,289.00,289
96,J,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287
97,J,M12,98,Flushing Av,Bk,40.700260,-73.941126,285.01,285
98,J,M13,99,Lorimer St,Bk,40.703869,-73.947408,491.00,491
99,J,M14,100,Hewes St,Bk,40.706870,-73.953431,529.00,529
100,J,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529
101,J,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18
102,J,M19,103,Bowery,M,40.720280,-73.993915,18.00,18
103,J,M20,104,Canal St,M,40.718092,-73.999892,41.00,41
104,J,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29
105,J,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15
106,J,M23,107,Broad St,M,40.706476,-74.011056,7.00,7
278,J,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246
279,J,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208

In [88]:
stations_expanded[stations_expanded['Daytime Routes'] == 'Z']

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
79,Z,J12,80,121 St,Q,40.700492,-73.828294,144.00,144
81,Z,J14,82,104 St,Q,40.695178,-73.844330,26.00,26
82,Z,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20
84,Z,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4
86,Z,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178
87,Z,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174
89,Z,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198
90,Z,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198
91,Z,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405
92,Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369
94,Z,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397
96,Z,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287
100,Z,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529
101,Z,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18
102,Z,M19,103,Bowery,M,40.720280,-73.993915,18.00,18
103,Z,M20,104,Canal St,M,40.718092,-73.999892,41.00,41
104,Z,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29
105,Z,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15
106,Z,M23,107,Broad St,M,40.706476,-74.011056,7.00,7
278,Z,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246
279,Z,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208

In [89]:
stations_expanded.value_counts('Daytime Routes')

Daytime Routes
2      49
F      45
R      45
5      45
A      44
C      40
1      38
6      38
B      37
D      36
M      36
3      34
J      30
Q      29
4      28
N      28
L      24
W      23
7      22
E      22
G      21
SIR    21
Z      21
S      11
Name: count, dtype: int64

In [90]:
len(stations_expanded['Daytime Routes'].unique())

24

## Reading in Subway Performance Data:

In [91]:
mta_metrics = pd.read_csv('../cleaned_data/MTA_Subway_Performance.csv', low_memory=False)

mta_metrics['Daytime Routes'].value_counts()

Daytime Routes
1     189
2     189
RS    189
FS    189
R     189
Q     189
N     189
M     189
L     189
G     189
F     189
E     189
D     189
7     189
6     189
5     189
4     189
3     189
A     188
C     187
GS    180
B     118
J     112
Z      77
W      18
Name: count, dtype: int64

In [92]:
type(mta_metrics['line'][5])

str

In [93]:
mta_metrics.head()

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance,Daytime Routes
0,2015-01-01,A DIVISION,1,1,6874,9017,76.233781,1
1,2015-01-01,A DIVISION,2,1,2920,6175,47.287449,2
2,2015-01-01,A DIVISION,3,1,4004,5834,68.632156,3
3,2015-01-01,A DIVISION,4,1,3692,7623,48.432376,4
4,2015-01-01,A DIVISION,5,1,3203,6491,49.345247,5

## Assigning 'S' stations one of 3 shuttle designations: RS, FS, or GS:

In [94]:
stations_expanded[stations_expanded['Daytime Routes'] == 'S']

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
41,S,D26,42,Prospect Park,Bk,40.661614,-73.962246,327.00,327
138,S,S01,139,Franklin Av,Bk,40.680596,-73.955827,227.00,227
139,S,S03,141,Park Pl,Bk,40.674772,-73.957624,305.00,305
140,S,S04,142,Botanic Garden,Bk,40.670343,-73.959245,213.00,213
199,S,H04,199,Broad Channel,Q,40.608382,-73.815925,1072.01,1072
200,S,H12,200,Beach 90 St,Q,40.588034,-73.813641,942.02,942
201,S,H13,201,Beach 98 St,Q,40.585307,-73.820558,942.01,942
202,S,H14,202,Beach 105 St,Q,40.583209,-73.827559,938.00,938
203,S,H15,203,Rockaway Park-Beach 116 St,Q,40.580903,-73.835592,938.00,938
469,S,902,468,Times Sq-42 St,M,40.755983,-73.986229,119.00,119
470,S,901,469,Grand Central-42 St,M,40.752769,-73.979189,94.00,94

In [95]:
def update_daytime_routes(row):
    if 'S' not in row['Daytime Routes']:
        return row['Daytime Routes']
    
    if row['Borough'] == 'M':
        return 'GS'
    elif row['Borough'] == 'Bk':
        return 'FS'
    elif row['Borough'] == 'Q':
        return 'RS'
    else:
        return row['Daytime Routes']

stations_expanded['Daytime Routes'] = stations_expanded.apply(update_daytime_routes, axis=1)

In [96]:
stations_expanded['Daytime Routes'].value_counts()

Daytime Routes
2      49
R      45
F      45
5      45
A      44
C      40
1      38
6      38
B      37
D      36
M      36
3      34
J      30
Q      29
4      28
N      28
L      24
W      23
E      22
7      22
G      21
Z      21
SIR    21
RS      5
FS      4
GS      2
Name: count, dtype: int64

In [97]:
len(stations_expanded['Daytime Routes'].unique())

26

# Note:
- going to ignore SIR moving forward as we do not have any metrics associated with the Staten Island trains


## Process:
- Create a dictionary of subway lines
- Populate with: 
* station_expanded[[Census Tract Whole', 'Borough', 'Stop Name']] 
**AND** 
* mta_metrics[['month', 'terminal_on_time_performance']]     (mapped on='Daytime Routes')

- Export into new file

In [98]:
stations_grouped = stations_expanded.groupby('Daytime Routes').agg(
    num_stations = ('Daytime Routes', 'count'),
    station_census_tracts = ('Census Tract Whole', lambda x: x.tolist()),
    station_boroughs = ('Borough', lambda x: x.tolist()),
    stop_names = ('Stop Name', lambda x: x.tolist())
)

stations_grouped

,num_stations,station_census_tracts,station_boroughs,stop_names
Daytime Routes,,,,
1,38,"[285, 283, 283, 309, 303, 293, 283, 277, 269, ...","[Bx, Bx, Bx, M, M, M, M, M, M, M, M, M, M, M, ...","[Van Cortlandt Park-242 St, 238 St, 231 St, Ma..."
2,49,"[183, 159, 113, 101, 71, 21, 21, 15, 7, 5, 11,...","[M, M, M, M, M, M, M, M, M, Bk, Bk, Bk, Bk, Bk...","[96 St, 72 St, Times Sq-42 St, 34 St-Penn Stat..."
3,34,"[183, 159, 113, 101, 71, 21, 21, 15, 7, 5, 11,...","[M, M, M, M, M, M, M, M, M, Bk, Bk, Bk, Bk, Bk...","[96 St, 72 St, Times Sq-42 St, 34 St-Penn Stat..."
4,28,"[37, 35, 213, 351, 431, 419, 409, 403, 401, 23...","[Bk, Bk, Bk, Bk, Bx, Bx, Bx, Bx, Bx, Bx, Bx, B...","[Nevins St, Atlantic Av-Barclays Ctr, Franklin..."
5,45,"[37, 35, 213, 319, 329, 804, 820, 826, 830, 78...","[Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bx, M...","[Nevins St, Atlantic Av-Barclays Ctr, Franklin..."
6,38,"[300, 266, 266, 200, 96, 206, 72, 70, 48, 54, ...","[Bx, Bx, Bx, Bx, Bx, Bx, Bx, Bx, Bx, Bx, Bx, B...","[Pelham Bay Park, Buhre Av, Middletown Rd, Wes..."
7,22,"[871, 383, 401, 405, 465, 277, 283, 267, 263, ...","[Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, ...","[Flushing-Main St, Mets-Willets Point, 111 St,..."
A,44,"[293, 287, 281, 273, 263, 251, 231, 209, 145, ...","[M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, ...","[Inwood-207 St, Dyckman St, 190 St, 181 St, 17..."
B,37,"[15, 35, 161, 327, 506, 520, 552, 606, 360, 23...","[Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, M, M, M, ...","[DeKalb Av, Atlantic Av-Barclays Ctr, 7 Av, Pr..."
C,40,"[251, 243, 235, 231, 217, 209, 218, 197, 189, ...","[M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, ...","[168 St, 163 St-Amsterdam Av, 155 St, 145 St, ..."
D,36,"[39, 84, 350, 110, 112, 220, 240, 250, 190, 18...","[Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, B...","[Atlantic Av-Barclays Ctr, 36 St, Coney Island..."
E,22,"[133, 119, 109, 91, 81, 71, 49, 33, 21, 216, 3...","[M, M, M, M, M, M, M, M, M, Q, Q, Q, Q, Q, Q, ...","[50 St, 42 St-Port Authority Bus Terminal, 34 ..."
F,45,"[354, 350, 71, 11, 125, 113, 101, 58, 81, 55, ...","[Bk, Bk, M, Bk, M, M, M, M, M, M, M, M, M, Bk,...","[W 8 St-NY Aquarium, Coney Island-Stillwell Av..."
FS,4,"[327, 227, 305, 213]","[Bk, Bk, Bk, Bk]","[Prospect Park, Franklin Av, Park Pl, Botanic ..."
G,21,"[41, 69, 77, 119, 121, 151, 169, 504, 496, 19,...","[Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Q, Q, Bk,...","[Hoyt-Schermerhorn Sts, Bergen St, Carroll St,..."
GS,2,"[119, 94]","[M, M]","[Times Sq-42 St, Grand Central-42 St]"
J,30,"[144, 124, 26, 20, 12, 4, 1182, 1178, 1174, 11...","[Q, Q, Q, Q, Q, Q, Bk, Bk, Bk, Bk, Bk, Bk, Bk,...","[121 St, 111 St, 104 St, Woodhaven Blvd, 85 St..."
L,24,"[83, 63, 61, 48, 34, 553, 513, 497, 495, 493, ...","[M, M, M, M, M, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk...","[8 Av, 6 Av, 14 St-Union Sq, 3 Av, 1 Av, Bedfo..."
M,36,"[287, 285, 491, 529, 529, 18, 613, 613, 589, 5...","[Bk, Bk, Bk, Bk, Bk, M, Q, Q, Q, Q, Bk, Bk, Bk...","[Myrtle Av, Flushing Av, Lorimer St, Hewes St,..."
N,28,"[115, 125, 63, 59, 53, 31, 114, 143, 137, 125,...","[Q, Q, Q, Q, Q, Q, M, M, M, M, M, M, M, M, Bk,...","[Astoria-Ditmars Blvd, Astoria Blvd, 30 Av, Br..."
Q,29,"[137, 113, 101, 52, 45, 15, 35, 161, 327, 798,...","[M, M, M, M, M, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk...","[57 St-7 Av, Times Sq-42 St, 34 St-Herald Sq, ..."
R,45,"[114, 143, 137, 125, 113, 101, 76, 56, 52, 57,...","[M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, ...","[Lexington Av/59 St, 5 Av/59 St, 57 St-7 Av, 4..."
RS,5,"[1072, 942, 942, 938, 938]","[Q, Q, Q, Q, Q]","[Broad Channel, Beach 90 St, Beach 98 St, Beac..."
SIR,21,"[3, 21, 21, 6, 50, 96, 96, 114, 122, 134, 132,...","[SI, SI, SI, SI, SI, SI, SI, SI, SI, SI, SI, S...","[St George, Tompkinsville, Stapleton, Clifton,..."
W,23,"[115, 125, 63, 59, 53, 31, 114, 143, 137, 125,...","[Q, Q, Q, Q, Q, Q, M, M, M, M, M, M, M, M, M, ...","[Astoria-Ditmars Blvd, Astoria Blvd, 30 Av, Br..."
Z,21,"[144, 26, 20, 4, 1178, 1174, 1198, 1198, 405, ...","[Q, Q, Q, Q, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, B...","[121 St, 104 St, Woodhaven Blvd, 75 St-Elderts..."

In [99]:
stations_list = stations_grouped.index.to_list()
stations_list

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'FS',
 'G',
 'GS',
 'J',
 'L',
 'M',
 'N',
 'Q',
 'R',
 'RS',
 'SIR',
 'W',
 'Z']

In [100]:
stations_grouped.loc['Z']

num_stations                                                            21
station_census_tracts    [144, 26, 20, 4, 1178, 1174, 1198, 1198, 405, ...
station_boroughs         [Q, Q, Q, Q, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, B...
stop_names               [121 St, 104 St, Woodhaven Blvd, 75 St-Elderts...
Name: Z, dtype: object

In [101]:
def grouped_to_dict(grouped_df):
    """
    Convert a grouped DataFrame into a dictionary where:
    - Key: the group name (station/route)
    - Value: dictionary containing all grouped data
    """
    result = {}
    for station, row in grouped_df.iterrows():
        result[station] = row.to_dict()
    return result

subway_dict = grouped_to_dict(stations_grouped)
subway_dict['J']

{'num_stations': 30,
 'station_census_tracts': [144,
  124,
  26,
  20,
  12,
  4,
  1182,
  1178,
  1174,
  1168,
  1198,
  1198,
  405,
  369,
  397,
  397,
  289,
  287,
  285,
  491,
  529,
  529,
  18,
  18,
  41,
  29,
  15,
  7,
  246,
  208],
 'station_boroughs': ['Q',
  'Q',
  'Q',
  'Q',
  'Q',
  'Q',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'M',
  'M',
  'M',
  'M',
  'M',
  'M',
  'Q',
  'Q'],
 'stop_names': ['121 St',
  '111 St',
  '104 St',
  'Woodhaven Blvd',
  '85 St-Forest Pkwy',
  '75 St-Elderts Ln',
  'Cypress Hills',
  'Crescent St',
  'Norwood Av',
  'Cleveland St',
  'Van Siclen Av',
  'Alabama Av',
  'Broadway Junction',
  'Chauncey St',
  'Halsey St',
  'Gates Av',
  'Kosciuszko St',
  'Myrtle Av',
  'Flushing Av',
  'Lorimer St',
  'Hewes St',
  'Marcy Av',
  'Delancey St-Essex St',
  'Bowery',
  'Canal St',
  'Chambers St',
  'Fulton St',
  'Broad St',
  'Jamaica Center-Parsons/Archer',
  'Sutphin Blvd-Archer Av-JFK Airport']}

In [102]:
for indx, row in mta_metrics.iterrows():
    if row['line'] in subway_dict:
        if 'mta_performance_data' not in subway_dict[row['line']]:
            subway_dict[row['line']]['mta_performance_data'] = []
        subway_dict[row['line']]['mta_performance_data'].append([row['month'], row['terminal_on_time_performance'], row['day_type']])

In [103]:
subway_dict['A']['mta_performance_data'][:5]

[['2015-01-01', 67.6402347, 1],
 ['2015-02-01', 62.9842181, 1],
 ['2015-03-01', 65.5597015, 1],
 ['2015-04-01', 71.2515489, 1],
 ['2015-05-01', 67.3497082, 1]]

In [104]:
subway_df = pd.DataFrame.from_dict(subway_dict, orient='index')

subway_df.tail()

,num_stations,station_census_tracts,station_boroughs,stop_names,mta_performance_data
R,45,"[114, 143, 137, 125, 113, 101, 76, 56, 52, 57,...","[M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, ...","[Lexington Av/59 St, 5 Av/59 St, 57 St-7 Av, 4...","[[2015-01-01, 61.8342152, 1], [2015-02-01, 57...."
RS,5,"[1072, 942, 942, 938, 938]","[Q, Q, Q, Q, Q]","[Broad Channel, Beach 90 St, Beach 98 St, Beac...","[[2015-01-01, 95.3841572, 1], [2015-02-01, 94...."
SIR,21,"[3, 21, 21, 6, 50, 96, 96, 114, 122, 134, 132,...","[SI, SI, SI, SI, SI, SI, SI, SI, SI, SI, SI, S...","[St George, Tompkinsville, Stapleton, Clifton,...",NaN
W,23,"[115, 125, 63, 59, 53, 31, 114, 143, 137, 125,...","[Q, Q, Q, Q, Q, Q, M, M, M, M, M, M, M, M, M, ...","[Astoria-Ditmars Blvd, Astoria Blvd, 30 Av, Br...","[[2016-11-01, 76.5017118, 1], [2016-12-01, 64...."
Z,21,"[144, 26, 20, 4, 1178, 1174, 1198, 1198, 405, ...","[Q, Q, Q, Q, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, B...","[121 St, 104 St, Woodhaven Blvd, 75 St-Elderts...",NaN

In [107]:
subway_df.loc['R']['mta_performance_data'][:5]

[['2015-01-01', 61.8342152, 1],
 ['2015-02-01', 57.7732266, 1],
 ['2015-03-01', 57.8104994, 1],
 ['2015-04-01', 60.1632522, 1],
 ['2015-05-01', 55.3169014, 1]]

In [108]:
subway_df.to_csv('../cleaned_data/MTA_Subway_Grouped_Data.csv', index_label='line')