# MTA Subway Line Groupings

## Goal:
- Group the subway stations into their respective train lines:

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

stations = pd.read_csv('../cleaned_data/MTA_Subway_Stations_w_Tracts+Zip_2025.csv', low_memory=False)

stations.shape

(496, 10)

In [2]:
stations[stations['Daytime Routes'].str.contains('J', na=False)]

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole,zip_code
79,J Z,J12,80,121 St,Q,40.700492,-73.828294,144.00,144,11415
80,J,J13,81,111 St,Q,40.697418,-73.836345,124.00,124,11418
81,J Z,J14,82,104 St,Q,40.695178,-73.844330,26.00,26,11418
82,J Z,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20,11421
83,J,J16,84,85 St-Forest Pkwy,Q,40.692435,-73.860010,12.00,12,11421
84,J Z,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4,11421
85,J,J19,86,Cypress Hills,Bk,40.689941,-73.872550,1182.01,1182,11421
86,J Z,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178,11208
87,J Z,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174,11208
88,J,J22,89,Cleveland St,Bk,40.679947,-73.884639,1168.00,1168,11208
89,J Z,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198,11207
90,J Z,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198,11207
91,J Z,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405,11207
92,J Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369,11233
93,J,J29,94,Halsey St,Bk,40.686370,-73.916559,397.00,397,11233
94,J Z,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397,11221
95,J,J31,96,Kosciuszko St,Bk,40.693342,-73.928814,289.00,289,11221
96,M J Z,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287,11206
97,M J,M12,98,Flushing Av,Bk,40.700260,-73.941126,285.01,285,11206
98,M J,M13,99,Lorimer St,Bk,40.703869,-73.947408,491.00,491,11206
99,M J,M14,100,Hewes St,Bk,40.706870,-73.953431,529.00,529,11211
100,M J Z,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529,11249
101,M J Z,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18,10002
102,J Z,M19,103,Bowery,M,40.720280,-73.993915,18.00,18,10012
103,J Z,M20,104,Canal St,M,40.718092,-73.999892,41.00,41,10278
104,J Z,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29,10278
105,J Z,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15,10279
106,J Z,M23,107,Broad St,M,40.706476,-74.011056,7.00,7,10271
278,E J Z,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246,11451
279,E J Z,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208,11435

In [3]:
stations[stations['Daytime Routes'].str.contains('Z', na=False)]

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole,zip_code
79,J Z,J12,80,121 St,Q,40.700492,-73.828294,144.00,144,11415
81,J Z,J14,82,104 St,Q,40.695178,-73.844330,26.00,26,11418
82,J Z,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20,11421
84,J Z,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4,11421
86,J Z,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178,11208
87,J Z,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174,11208
89,J Z,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198,11207
90,J Z,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198,11207
91,J Z,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405,11207
92,J Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369,11233
94,J Z,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397,11221
96,M J Z,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287,11206
100,M J Z,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529,11249
101,M J Z,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18,10002
102,J Z,M19,103,Bowery,M,40.720280,-73.993915,18.00,18,10012
103,J Z,M20,104,Canal St,M,40.718092,-73.999892,41.00,41,10278
104,J Z,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29,10278
105,J Z,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15,10279
106,J Z,M23,107,Broad St,M,40.706476,-74.011056,7.00,7,10271
278,E J Z,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246,11451
279,E J Z,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208,11435

# Note:
- Z always appears with J (it is the express train w.r.t. the J train)

In [5]:
# Split rows into multiple rows based on 'Daytime Routes' column
stations_expanded = stations.assign(**{
    'Daytime Routes': stations['Daytime Routes'].str.split(' ')
}).explode('Daytime Routes')
stations_expanded.sample(10)

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole,zip_code
322,1,132,322,14 St,M,40.737826,-74.000201,71.00,71,10011
14,W,R20,15,14 St-Union Sq,M,40.735736,-73.990568,52.00,52,10003
92,Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369,11233
490,SIR,S16,516,Huguenot,SI,40.533674,-74.191794,170.05,170,10312
465,7,721,464,Vernon Blvd-Jackson Av,Q,40.742626,-73.953581,7.01,7,11109
338,4,235,338,Atlantic Av-Barclays Ctr,Bk,40.684359,-73.977666,35.00,35,11217
266,M,G13,266,Elmhurst Av,Q,40.742454,-73.882017,271.01,271,11373
10,Q,R16,11,Times Sq-42 St,M,40.754672,-73.986754,113.00,113,10110
364,6,606,364,Zerega Av,Bx,40.836488,-73.847036,96.00,96,10461
261,M,G08,261,Forest Hills-71 Av,Q,40.721691,-73.844521,739.00,739,11375

In [6]:
stations_expanded.shape

(767, 10)

In [7]:
stations_expanded[stations_expanded['Daytime Routes'] == 'J']

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole,zip_code
79,J,J12,80,121 St,Q,40.700492,-73.828294,144.00,144,11415
80,J,J13,81,111 St,Q,40.697418,-73.836345,124.00,124,11418
81,J,J14,82,104 St,Q,40.695178,-73.844330,26.00,26,11418
82,J,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20,11421
83,J,J16,84,85 St-Forest Pkwy,Q,40.692435,-73.860010,12.00,12,11421
84,J,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4,11421
85,J,J19,86,Cypress Hills,Bk,40.689941,-73.872550,1182.01,1182,11421
86,J,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178,11208
87,J,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174,11208
88,J,J22,89,Cleveland St,Bk,40.679947,-73.884639,1168.00,1168,11208
89,J,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198,11207
90,J,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198,11207
91,J,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405,11207
92,J,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369,11233
93,J,J29,94,Halsey St,Bk,40.686370,-73.916559,397.00,397,11233
94,J,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397,11221
95,J,J31,96,Kosciuszko St,Bk,40.693342,-73.928814,289.00,289,11221
96,J,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287,11206
97,J,M12,98,Flushing Av,Bk,40.700260,-73.941126,285.01,285,11206
98,J,M13,99,Lorimer St,Bk,40.703869,-73.947408,491.00,491,11206
99,J,M14,100,Hewes St,Bk,40.706870,-73.953431,529.00,529,11211
100,J,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529,11249
101,J,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18,10002
102,J,M19,103,Bowery,M,40.720280,-73.993915,18.00,18,10012
103,J,M20,104,Canal St,M,40.718092,-73.999892,41.00,41,10278
104,J,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29,10278
105,J,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15,10279
106,J,M23,107,Broad St,M,40.706476,-74.011056,7.00,7,10271
278,J,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246,11451
279,J,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208,11435

In [8]:
stations_expanded[stations_expanded['Daytime Routes'] == 'Z']

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole,zip_code
79,Z,J12,80,121 St,Q,40.700492,-73.828294,144.00,144,11415
81,Z,J14,82,104 St,Q,40.695178,-73.844330,26.00,26,11418
82,Z,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20,11421
84,Z,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4,11421
86,Z,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178,11208
87,Z,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174,11208
89,Z,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198,11207
90,Z,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198,11207
91,Z,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405,11207
92,Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369,11233
94,Z,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397,11221
96,Z,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287,11206
100,Z,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529,11249
101,Z,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18,10002
102,Z,M19,103,Bowery,M,40.720280,-73.993915,18.00,18,10012
103,Z,M20,104,Canal St,M,40.718092,-73.999892,41.00,41,10278
104,Z,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29,10278
105,Z,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15,10279
106,Z,M23,107,Broad St,M,40.706476,-74.011056,7.00,7,10271
278,Z,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246,11451
279,Z,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208,11435

In [9]:
stations_expanded.value_counts('Daytime Routes')

Daytime Routes
2      49
F      45
R      45
5      45
A      44
C      40
1      38
6      38
B      37
D      36
M      36
3      34
J      30
Q      29
4      28
N      28
L      24
W      23
7      22
E      22
G      21
SIR    21
Z      21
S      11
Name: count, dtype: int64

In [10]:
len(stations_expanded['Daytime Routes'].unique())

24

## Reading in Subway Performance Data:

In [11]:
mta_metrics = pd.read_csv('../cleaned_data/MTA_Subway_Performance.csv', low_memory=False)

mta_metrics['Daytime Routes'].value_counts()

Daytime Routes
1     189
2     189
RS    189
FS    189
R     189
Q     189
N     189
M     189
L     189
G     189
F     189
E     189
D     189
7     189
6     189
5     189
4     189
3     189
A     188
C     187
GS    180
B     118
J     112
Z      77
W      18
Name: count, dtype: int64

In [12]:
type(mta_metrics['line'][5])

str

In [19]:
mta_metrics.sample(10)

,month,division,line,day_type,num_on_time_trips,num_sched_trips,terminal_on_time_performance,Daytime Routes
3277,2021-11-01,B DIVISION,B,1,2928,4116,71.137030,B
1177,2019-03-01,B DIVISION,B,1,2440,4016,60.756972,B
101,2015-05-01,B DIVISION,B,1,3178,4120,77.135922,B
2891,2022-08-01,B DIVISION,L,1,11579,12552,92.248250,L
1768,2024-09-01,B DIVISION,R,2,1874,2154,87.000930,R
113,2015-05-01,B DIVISION,FS,1,2360,2360,100.000000,FS
1459,2019-09-01,B DIVISION,RS,1,2832,2940,96.326531,RS
793,2017-10-01,B DIVISION,W,1,2907,4158,69.913420,W
921,2018-04-01,A DIVISION,GS,1,13036,13156,99.087869,GS
2240,2023-10-01,B DIVISION,A,2,2477,3140,78.885350,A

## Assigning 'S' stations one of 3 shuttle designations: RS, FS, or GS:

In [20]:
stations_expanded[stations_expanded['Daytime Routes'] == 'S']

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole,zip_code
41,S,D26,42,Prospect Park,Bk,40.661614,-73.962246,327.00,327,11225
138,S,S01,139,Franklin Av,Bk,40.680596,-73.955827,227.00,227,11216
139,S,S03,141,Park Pl,Bk,40.674772,-73.957624,305.00,305,11238
140,S,S04,142,Botanic Garden,Bk,40.670343,-73.959245,213.00,213,11238
199,S,H04,199,Broad Channel,Q,40.608382,-73.815925,1072.01,1072,11693
200,S,H12,200,Beach 90 St,Q,40.588034,-73.813641,942.02,942,11693
201,S,H13,201,Beach 98 St,Q,40.585307,-73.820558,942.01,942,11693
202,S,H14,202,Beach 105 St,Q,40.583209,-73.827559,938.00,938,11693
203,S,H15,203,Rockaway Park-Beach 116 St,Q,40.580903,-73.835592,938.00,938,11694
469,S,902,468,Times Sq-42 St,M,40.755983,-73.986229,119.00,119,10110
470,S,901,469,Grand Central-42 St,M,40.752769,-73.979189,94.00,94,10165

In [21]:
def update_daytime_routes(row):
    if 'S' not in row['Daytime Routes']:
        return row['Daytime Routes']
    
    if row['Borough'] == 'M':
        return 'GS'
    elif row['Borough'] == 'Bk':
        return 'FS'
    elif row['Borough'] == 'Q':
        return 'RS'
    else:
        return row['Daytime Routes']

stations_expanded['Daytime Routes'] = stations_expanded.apply(update_daytime_routes, axis=1)

In [22]:
stations_expanded['Daytime Routes'].value_counts()

Daytime Routes
2      49
R      45
F      45
5      45
A      44
C      40
1      38
6      38
B      37
D      36
M      36
3      34
J      30
Q      29
4      28
N      28
L      24
W      23
E      22
7      22
G      21
Z      21
SIR    21
RS      5
FS      4
GS      2
Name: count, dtype: int64

In [23]:
len(stations_expanded['Daytime Routes'].unique())

26

# Note:
- going to ignore SIR moving forward as we do not have any metrics associated with the Staten Island trains


## Process:
- Create a dictionary of subway lines
- Populate with: 
* station_expanded[[Census Tract Whole', 'Borough', 'Stop Name']] 
**AND** 
* mta_metrics[['month', 'terminal_on_time_performance']]     (mapped on='Daytime Routes')

- Export into new file

In [24]:
stations_grouped = stations_expanded.groupby('Daytime Routes').agg(
    num_stations = ('Daytime Routes', 'count'),
    station_latitudes = ('GTFS Latitude', lambda x: x.tolist()),
    station_longitudes = ('GTFS Longitude', lambda x: x.tolist()),
    station_census_tracts = ('Census Tract Whole', lambda x: x.tolist()),
    station_zip_codes = ('zip_code', lambda x: x.tolist()),
    station_boroughs = ('Borough', lambda x: x.tolist()),
    stop_names = ('Stop Name', lambda x: x.tolist())
)

stations_grouped

,num_stations,station_latitudes,station_longitudes,station_census_tracts,station_zip_codes,station_boroughs,stop_names
Daytime Routes,,,,,,,
1,38,"[40.889248, 40.884667, 40.878856, 40.874561, 4...","[-73.898583, -73.90087, -73.904834, -73.909831...","[285, 283, 283, 309, 303, 293, 283, 277, 269, ...","[10463, 10463, 10463, 10468, 10034, 10034, 100...","[Bx, Bx, Bx, M, M, M, M, M, M, M, M, M, M, M, ...","[Van Cortlandt Park-242 St, 238 St, 231 St, Ma..."
2,49,"[40.793919, 40.778453, 40.75529, 40.750373, 40...","[-73.972323, -73.98197, -73.987495, -73.991057...","[183, 159, 113, 101, 71, 21, 21, 15, 7, 5, 11,...","[10025, 10023, 10018, 10119, 10011, 10007, 102...","[M, M, M, M, M, M, M, M, M, Bk, Bk, Bk, Bk, Bk...","[96 St, 72 St, Times Sq-42 St, 34 St-Penn Stat..."
3,34,"[40.793919, 40.778453, 40.75529, 40.750373, 40...","[-73.972323, -73.98197, -73.987495, -73.991057...","[183, 159, 113, 101, 71, 21, 21, 15, 7, 5, 11,...","[10025, 10023, 10018, 10119, 10011, 10007, 102...","[M, M, M, M, M, M, M, M, M, Bk, Bk, Bk, Bk, Bk...","[96 St, 72 St, Times Sq-42 St, 34 St-Penn Stat..."
4,28,"[40.688246, 40.684359, 40.670682, 40.668897, 4...","[-73.980492, -73.977666, -73.958131, -73.93294...","[37, 35, 213, 351, 431, 419, 409, 403, 401, 23...","[11217, 11217, 11238, 11213, 10467, 10467, 104...","[Bk, Bk, Bk, Bk, Bx, Bx, Bx, Bx, Bx, Bx, Bx, B...","[Nevins St, Atlantic Av-Barclays Ctr, Franklin..."
5,45,"[40.688246, 40.684359, 40.670682, 40.667883, 4...","[-73.980492, -73.977666, -73.958131, -73.95068...","[37, 35, 213, 319, 329, 804, 820, 826, 830, 78...","[11217, 11217, 11238, 11225, 11225, 11225, 112...","[Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bx, M...","[Nevins St, Atlantic Av-Barclays Ctr, Franklin..."
6,38,"[40.852462, 40.84681, 40.843863, 40.839892, 40...","[-73.828121, -73.832569, -73.836322, -73.84295...","[300, 266, 266, 200, 96, 206, 72, 70, 48, 54, ...","[10461, 10461, 10461, 10461, 10461, 10462, 104...","[Bx, Bx, Bx, Bx, Bx, Bx, Bx, Bx, Bx, Bx, Bx, B...","[Pelham Bay Park, Buhre Av, Middletown Rd, Wes..."
7,22,"[40.7596, 40.754622, 40.75173, 40.749865, 40.7...","[-73.83003, -73.845625, -73.855334, -73.8627, ...","[871, 383, 401, 405, 465, 277, 283, 267, 263, ...","[11354, 11368, 11368, 11368, 11373, 11372, 113...","[Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, Q, ...","[Flushing-Main St, Mets-Willets Point, 111 St,..."
A,44,"[40.868072, 40.865491, 40.859022, 40.851695, 4...","[-73.919899, -73.927271, -73.93418, -73.937969...","[293, 287, 281, 273, 263, 251, 231, 209, 145, ...","[10034, 10034, 10040, 10033, 10033, 10032, 100...","[M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, ...","[Inwood-207 St, Dyckman St, 190 St, 181 St, 17..."
B,37,"[40.690635, 40.68446, 40.67705, 40.661614, 40....","[-73.981824, -73.97689, -73.972367, -73.962246...","[15, 35, 161, 327, 506, 520, 552, 606, 360, 23...","[11217, 11217, 11238, 11225, 11226, 11226, 112...","[Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, M, M, M, ...","[DeKalb Av, Atlantic Av-Barclays Ctr, 7 Av, Pr..."
C,40,"[40.840719, 40.836013, 40.830518, 40.824783, 4...","[-73.939561, -73.939892, -73.941514, -73.94421...","[251, 243, 235, 231, 217, 209, 218, 197, 189, ...","[10032, 10032, 10039, 10031, 10030, 10027, 100...","[M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, ...","[168 St, 163 St-Amsterdam Av, 155 St, 145 St, ..."
D,36,"[40.683666, 40.655144, 40.577422, 40.646292, 4...","[-73.97881, -74.003549, -73.981233, -73.994324...","[39, 84, 350, 110, 112, 220, 240, 250, 190, 18...","[11217, 11232, 11224, 11219, 11219, 11219, 112...","[Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, B...","[Atlantic Av-Barclays Ctr, 36 St, Coney Island..."
E,22,"[40.762456, 40.757308, 40.752287, 40.745906, 4...","[-73.985984, -73.989735, -73.993391, -73.99804...","[133, 119, 109, 91, 81, 71, 49, 33, 21, 216, 3...","[10019, 10036, 10119, 10011, 10011, 10014, 100...","[M, M, M, M, M, M, M, M, M, Q, Q, Q, Q, Q, Q, ...","[50 St, 42 St-Port Authority Bus Terminal, 34 ..."
F,45,"[40.576127, 40.577422, 40.732338, 40.692338, 4...","[-73.975939, -73.981233, -74.000495, -73.98734...","[354, 350, 71, 11, 125, 113, 101, 58, 81, 55, ...","[11224, 11224, 10014, 11201, 10020, 10110, 101...","[Bk, Bk, M, Bk, M, M, M, M, M, M, M, M, M, Bk,...","[W 8 St-NY Aquarium, Coney Island-Stillwell Av..."
FS,4,"[40.661614, 40.680596, 40.674772, 40.670343]","[-73.962246, -73.955827, -73.957624, -73.959245]","[327, 227, 305, 213]","[11225, 11216, 11238, 11238]","[Bk, Bk, Bk, Bk]","[Prospect Park, Franklin Av, Park Pl, Botanic ..."
G,21,"[40.688484, 40.686145, 40.680303, 40.67358, 40...","[-73.985001, -73.990862, -73.995048, -73.99595...","[41, 69, 77, 119, 121, 151, 169, 504, 496, 19,...","[11201, 11201, 11231, 11231, 11215, 11215, 112...","[Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Q, Q, Bk,...","[Hoyt-Schermerhorn Sts, Bergen St, Carroll St,..."
GS,2,"[40.755983, 40.752769]","[-73.986229, -73.979189]","[119, 94]","[10110, 10165]","[M, M]","[Times Sq-42 St, Grand Central-42 St]"
J,30,"[40.700492, 40.697418, 40.695178, 40.693879, 4...","[-73.828294, -73.836345, -73.84433, -73.851576...","[144, 124, 26, 20, 12, 4, 1182, 1178, 1174, 11...","[11415, 11418, 11418, 11421, 11421, 11421, 114...","[Q, Q, Q, Q, Q, Q, Bk, Bk, Bk, Bk, Bk, Bk, Bk,...","[121 St, 111 St, 104 St, Woodhaven Blvd, 85 St..."
L,24,"[40.739777, 40.737335, 40.734789, 40.732849, 4...","[-74.002578, -73.996786, -73.99073, -73.986122...","[83, 63, 61, 48, 34, 553, 513, 497, 495, 493, ...","[10011, 10011, 10003, 10003, 10009, 11249, 112...","[M, M, M, M, M, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk...","[8 Av, 6 Av, 14 St-Union Sq, 3 Av, 1 Av, Bedfo..."
M,36,"[40.697207, 40.70026, 40.703869, 40.70687, 40....","[-73.935657, -73.941126, -73.947408, -73.95343...","[287, 285, 491, 529, 529, 18, 613, 613, 589, 5...","[11206, 11206, 11206, 11211, 11249, 10002, 113...","[Bk, Bk, Bk, Bk, Bk, M, Q, Q, Q, Q, Bk, Bk, Bk...","[Myrtle Av, Flushing Av, Lorimer St, Hewes St,..."
N,28,"[40.775036, 40.770258, 40.766779, 40.76182, 40...","[-73.912034, -73.917843, -73.921479, -73.92550...","[115, 125, 63, 59, 53, 31, 114, 143, 137, 125,...","[11105, 11102, 11102, 11106, 11106, 11101, 100...","[Q, Q, Q, Q, Q, Q, M, M, M, M, M, M, M, M, Bk,...","[Astoria-Ditmars Blvd, Astoria Blvd, 30 Av, Br..."
Q,29,"[40.764664, 40.754672, 40.749567, 40.735736, 4...","[-73.980658, -73.986754, -73.98795, -73.990568...","[137, 113, 101, 52, 45, 15, 35, 161, 327, 798,...","[10019, 10110, 10119, 10003, 10013, 11217, 112...","[M, M, M, M, M, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk...","[57 St-7 Av, Times Sq-42 St, 34 St-Herald Sq, ..."
R,45,"[40.76266, 40.764811, 40.764664, 40.759901, 40...","[-73.967258, -73.973347, -73.980658, -73.98413...","[114, 143, 137, 125, 113, 101, 76, 56, 52, 57,...","[10022, 10153, 10019, 10020, 10110, 10119, 101...","[M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, ...","[Lexington Av/59 St, 5 Av/59 St, 57 St-7 Av, 4..."
RS,5,"[40.608382, 40.588034, 40.585307, 40.583209, 4...","[-73.815925, -73.813641, -73.820558, -73.82755...","[1072, 942, 942, 938, 938]","[11693, 11693, 11693, 11693, 11694]","[Q, Q, Q, Q, Q]","[Broad Channel, Beach 90 St, Beach 98 St, Beac..."
SIR,21,"[40.643748, 40.636949, 40.627915, 40.621319, 4...","[-74.073643, -74.074835, -74.075162, -74.07140...","[3, 21, 21, 6, 50, 96, 96, 114, 122, 134, 132,...","[10301, 10301, 10301, 10301, 10304, 10304, 103...","[SI, SI, SI, SI, SI, SI, SI, SI, SI, SI, SI, S...","[St George, Tompkinsville, Stapleton, Clifton,..."
W,23,"[40.775036, 40.770258, 40.766779, 40.76182, 40...","[-73.912034, -73.917843, -73.921479, -73.92550...","[115, 125, 63, 59, 53, 31, 114, 143, 137, 125,...","[11105, 11102, 11102, 11106, 11106, 11101, 100...","[Q, Q, Q, Q, Q, Q, M, M, M, M, M, M, M, M, M, ...","[Astoria-Ditmars Blvd, Astoria Blvd, 30 Av, Br..."
Z,21,"[40.700492, 40.695178, 40.693879, 40.691324, 4...","[-73.828294, -73.84433, -73.851576, -73.867139...","[144, 26, 20, 4, 1178, 1174, 1198, 1198, 405, ...","[11415, 11418, 11421, 11421, 11208, 11208, 112...","[Q, Q, Q, Q, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, B...","[121 St, 104 St, Woodhaven Blvd, 75 St-Elderts..."

In [25]:
stations_list = stations_grouped.index.to_list()
stations_list

['1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'FS',
 'G',
 'GS',
 'J',
 'L',
 'M',
 'N',
 'Q',
 'R',
 'RS',
 'SIR',
 'W',
 'Z']

In [26]:
stations_grouped.loc['Z']

num_stations                                                            21
station_latitudes        [40.700492, 40.695178, 40.693879, 40.691324, 4...
station_longitudes       [-73.828294, -73.84433, -73.851576, -73.867139...
station_census_tracts    [144, 26, 20, 4, 1178, 1174, 1198, 1198, 405, ...
station_zip_codes        [11415, 11418, 11421, 11421, 11208, 11208, 112...
station_boroughs         [Q, Q, Q, Q, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, B...
stop_names               [121 St, 104 St, Woodhaven Blvd, 75 St-Elderts...
Name: Z, dtype: object

In [27]:
def grouped_to_dict(grouped_df):
    """
    Convert a grouped DataFrame into a dictionary where:
    - Key: the group name (station/route)
    - Value: dictionary containing all grouped data
    """
    result = {}
    for station, row in grouped_df.iterrows():
        result[station] = row.to_dict()
    return result

subway_dict = grouped_to_dict(stations_grouped)
subway_dict['J']

{'num_stations': 30,
 'station_latitudes': [40.700492,
  40.697418,
  40.695178,
  40.693879,
  40.692435,
  40.691324,
  40.689941,
  40.683194,
  40.68141,
  40.679947,
  40.678024,
  40.676992,
  40.679498,
  40.682893,
  40.68637,
  40.68963,
  40.693342,
  40.697207,
  40.70026,
  40.703869,
  40.70687,
  40.708359,
  40.718315,
  40.72028,
  40.718092,
  40.713243,
  40.710374,
  40.706476,
  40.702147,
  40.700486],
 'station_longitudes': [-73.828294,
  -73.836345,
  -73.84433,
  -73.851576,
  -73.86001,
  -73.867139,
  -73.87255,
  -73.873785,
  -73.880039,
  -73.884639,
  -73.891688,
  -73.898654,
  -73.904512,
  -73.910456,
  -73.916559,
  -73.92227,
  -73.928814,
  -73.935657,
  -73.941126,
  -73.947408,
  -73.953431,
  -73.957757,
  -73.987437,
  -73.993915,
  -73.999892,
  -74.003401,
  -74.007582,
  -74.011056,
  -73.801109,
  -73.807969],
 'station_census_tracts': [144,
  124,
  26,
  20,
  12,
  4,
  1182,
  1178,
  1174,
  1168,
  1198,
  1198,
  405,
  369,
  397,
  397,
  289,
  287,
  285,
  491,
  529,
  529,
  18,
  18,
  41,
  29,
  15,
  7,
  246,
  208],
 'station_zip_codes': [11415,
  11418,
  11418,
  11421,
  11421,
  11421,
  11421,
  11208,
  11208,
  11208,
  11207,
  11207,
  11207,
  11233,
  11233,
  11221,
  11221,
  11206,
  11206,
  11206,
  11211,
  11249,
  10002,
  10012,
  10278,
  10278,
  10279,
  10271,
  11451,
  11435],
 'station_boroughs': ['Q',
  'Q',
  'Q',
  'Q',
  'Q',
  'Q',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'Bk',
  'M',
  'M',
  'M',
  'M',
  'M',
  'M',
  'Q',
  'Q'],
 'stop_names': ['121 St',
  '111 St',
  '104 St',
  'Woodhaven Blvd',
  '85 St-Forest Pkwy',
  '75 St-Elderts Ln',
  'Cypress Hills',
  'Crescent St',
  'Norwood Av',
  'Cleveland St',
  'Van Siclen Av',
  'Alabama Av',
  'Broadway Junction',
  'Chauncey St',
  'Halsey St',
  'Gates Av',
  'Kosciuszko St',
  'Myrtle Av',
  'Flushing Av',
  'Lorimer St',
  'Hewes St',
  'Marcy Av',
  'Delancey St-Essex St',
  'Bowery',
  'Canal St',
  'Chambers St',
  'Fulton St',
  'Broad St',
  'Jamaica Center-Parsons/Archer',
  'Sutphin Blvd-Archer Av-JFK Airport']}

In [28]:
for indx, row in mta_metrics.iterrows():
    if row['line'] in subway_dict:
        if 'mta_performance_data' not in subway_dict[row['line']]:
            subway_dict[row['line']]['mta_performance_data'] = []
        subway_dict[row['line']]['mta_performance_data'].append([row['month'], row['terminal_on_time_performance'], row['day_type']])

In [29]:
subway_dict['A']['mta_performance_data'][:5]

[['2015-01-01', 67.6402347, 1],
 ['2015-02-01', 62.9842181, 1],
 ['2015-03-01', 65.5597015, 1],
 ['2015-04-01', 71.2515489, 1],
 ['2015-05-01', 67.3497082, 1]]

In [30]:
subway_df = pd.DataFrame.from_dict(subway_dict, orient='index')

subway_df.tail()

,num_stations,station_latitudes,station_longitudes,station_census_tracts,station_zip_codes,station_boroughs,stop_names,mta_performance_data
R,45,"[40.76266, 40.764811, 40.764664, 40.759901, 40...","[-73.967258, -73.973347, -73.980658, -73.98413...","[114, 143, 137, 125, 113, 101, 76, 56, 52, 57,...","[10022, 10153, 10019, 10020, 10110, 10119, 101...","[M, M, M, M, M, M, M, M, M, M, M, M, M, M, M, ...","[Lexington Av/59 St, 5 Av/59 St, 57 St-7 Av, 4...","[[2015-01-01, 61.8342152, 1], [2015-02-01, 57...."
RS,5,"[40.608382, 40.588034, 40.585307, 40.583209, 4...","[-73.815925, -73.813641, -73.820558, -73.82755...","[1072, 942, 942, 938, 938]","[11693, 11693, 11693, 11693, 11694]","[Q, Q, Q, Q, Q]","[Broad Channel, Beach 90 St, Beach 98 St, Beac...","[[2015-01-01, 95.3841572, 1], [2015-02-01, 94...."
SIR,21,"[40.643748, 40.636949, 40.627915, 40.621319, 4...","[-74.073643, -74.074835, -74.075162, -74.07140...","[3, 21, 21, 6, 50, 96, 96, 114, 122, 134, 132,...","[10301, 10301, 10301, 10301, 10304, 10304, 103...","[SI, SI, SI, SI, SI, SI, SI, SI, SI, SI, SI, S...","[St George, Tompkinsville, Stapleton, Clifton,...",NaN
W,23,"[40.775036, 40.770258, 40.766779, 40.76182, 40...","[-73.912034, -73.917843, -73.921479, -73.92550...","[115, 125, 63, 59, 53, 31, 114, 143, 137, 125,...","[11105, 11102, 11102, 11106, 11106, 11101, 100...","[Q, Q, Q, Q, Q, Q, M, M, M, M, M, M, M, M, M, ...","[Astoria-Ditmars Blvd, Astoria Blvd, 30 Av, Br...","[[2016-11-01, 76.5017118, 1], [2016-12-01, 64...."
Z,21,"[40.700492, 40.695178, 40.693879, 40.691324, 4...","[-73.828294, -73.84433, -73.851576, -73.867139...","[144, 26, 20, 4, 1178, 1174, 1198, 1198, 405, ...","[11415, 11418, 11421, 11421, 11208, 11208, 112...","[Q, Q, Q, Q, Bk, Bk, Bk, Bk, Bk, Bk, Bk, Bk, B...","[121 St, 104 St, Woodhaven Blvd, 75 St-Elderts...",NaN

In [31]:
subway_df.loc['R']['mta_performance_data'][:5]

[['2015-01-01', 61.8342152, 1],
 ['2015-02-01', 57.7732266, 1],
 ['2015-03-01', 57.8104994, 1],
 ['2015-04-01', 60.1632522, 1],
 ['2015-05-01', 55.3169014, 1]]

In [32]:
type(subway_df.loc['R']['station_zip_codes'][0])

int

In [33]:
subway_df.to_csv('../cleaned_data/MTA_Subway_Grouped_Data.csv', index_label='line')