# MTA Subway Line Groupings

## Goal:
- Group the subway stations into their respective train lines:

In [7]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

stations = pd.read_csv('../cleaned_data/MTA_Subway_Stations_With_Census_Tracts_2025.csv', low_memory=False)

stations.shape

(496, 9)

In [ ]:
stations[stations['Daytime Routes'].str.contains('J', na=False)]

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
79,J Z,J12,80,121 St,Q,40.700492,-73.828294,144.00,144
80,J,J13,81,111 St,Q,40.697418,-73.836345,124.00,124
81,J Z,J14,82,104 St,Q,40.695178,-73.844330,26.00,26
82,J Z,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20
83,J,J16,84,85 St-Forest Pkwy,Q,40.692435,-73.860010,12.00,12
84,J Z,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4
85,J,J19,86,Cypress Hills,Bk,40.689941,-73.872550,1182.01,1182
86,J Z,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178
87,J Z,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174
88,J,J22,89,Cleveland St,Bk,40.679947,-73.884639,1168.00,1168
89,J Z,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198
90,J Z,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198
91,J Z,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405
92,J Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369
93,J,J29,94,Halsey St,Bk,40.686370,-73.916559,397.00,397
94,J Z,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397
95,J,J31,96,Kosciuszko St,Bk,40.693342,-73.928814,289.00,289
96,M J Z,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287
97,M J,M12,98,Flushing Av,Bk,40.700260,-73.941126,285.01,285
98,M J,M13,99,Lorimer St,Bk,40.703869,-73.947408,491.00,491
99,M J,M14,100,Hewes St,Bk,40.706870,-73.953431,529.00,529
100,M J Z,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529
101,M J Z,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18
102,J Z,M19,103,Bowery,M,40.720280,-73.993915,18.00,18
103,J Z,M20,104,Canal St,M,40.718092,-73.999892,41.00,41
104,J Z,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29
105,J Z,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15
106,J Z,M23,107,Broad St,M,40.706476,-74.011056,7.00,7
278,E J Z,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246
279,E J Z,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208

In [21]:
stations[stations['Daytime Routes'].str.contains('Z', na=False)]

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
79,J Z,J12,80,121 St,Q,40.700492,-73.828294,144.00,144
81,J Z,J14,82,104 St,Q,40.695178,-73.844330,26.00,26
82,J Z,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20
84,J Z,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4
86,J Z,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178
87,J Z,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174
89,J Z,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198
90,J Z,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198
91,J Z,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405
92,J Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369
94,J Z,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397
96,M J Z,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287
100,M J Z,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529
101,M J Z,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18
102,J Z,M19,103,Bowery,M,40.720280,-73.993915,18.00,18
103,J Z,M20,104,Canal St,M,40.718092,-73.999892,41.00,41
104,J Z,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29
105,J Z,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15
106,J Z,M23,107,Broad St,M,40.706476,-74.011056,7.00,7
278,E J Z,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246
279,E J Z,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208

# Note:
- Z always appears with J (it is the express train w.r.t. the J train)

In [11]:
# Split rows into multiple rows based on 'Daytime Routes' column
stations_expanded = stations.assign(**{
    'Daytime Routes': stations['Daytime Routes'].str.split(' ')
}).explode('Daytime Routes')
stations_expanded.head()

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
0,N,R01,1,Astoria-Ditmars Blvd,Q,40.775036,-73.912034,115.0,115
0,W,R01,1,Astoria-Ditmars Blvd,Q,40.775036,-73.912034,115.0,115
1,N,R03,2,Astoria Blvd,Q,40.770258,-73.917843,125.0,125
1,W,R03,2,Astoria Blvd,Q,40.770258,-73.917843,125.0,125
2,N,R04,3,30 Av,Q,40.766779,-73.921479,63.0,63

In [10]:
stations_expanded.shape

(767, 9)

In [24]:
stations_expanded[stations_expanded['Daytime Routes'] == 'J']

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
79,J,J12,80,121 St,Q,40.700492,-73.828294,144.00,144
80,J,J13,81,111 St,Q,40.697418,-73.836345,124.00,124
81,J,J14,82,104 St,Q,40.695178,-73.844330,26.00,26
82,J,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20
83,J,J16,84,85 St-Forest Pkwy,Q,40.692435,-73.860010,12.00,12
84,J,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4
85,J,J19,86,Cypress Hills,Bk,40.689941,-73.872550,1182.01,1182
86,J,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178
87,J,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174
88,J,J22,89,Cleveland St,Bk,40.679947,-73.884639,1168.00,1168
89,J,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198
90,J,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198
91,J,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405
92,J,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369
93,J,J29,94,Halsey St,Bk,40.686370,-73.916559,397.00,397
94,J,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397
95,J,J31,96,Kosciuszko St,Bk,40.693342,-73.928814,289.00,289
96,J,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287
97,J,M12,98,Flushing Av,Bk,40.700260,-73.941126,285.01,285
98,J,M13,99,Lorimer St,Bk,40.703869,-73.947408,491.00,491
99,J,M14,100,Hewes St,Bk,40.706870,-73.953431,529.00,529
100,J,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529
101,J,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18
102,J,M19,103,Bowery,M,40.720280,-73.993915,18.00,18
103,J,M20,104,Canal St,M,40.718092,-73.999892,41.00,41
104,J,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29
105,J,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15
106,J,M23,107,Broad St,M,40.706476,-74.011056,7.00,7
278,J,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246
279,J,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208

In [23]:
stations_expanded[stations_expanded['Daytime Routes'] == 'Z']

,Daytime Routes,GTFS Stop ID,Station ID,Stop Name,Borough,GTFS Latitude,GTFS Longitude,Census Tract,Census Tract Whole
79,Z,J12,80,121 St,Q,40.700492,-73.828294,144.00,144
81,Z,J14,82,104 St,Q,40.695178,-73.844330,26.00,26
82,Z,J15,83,Woodhaven Blvd,Q,40.693879,-73.851576,20.00,20
84,Z,J17,85,75 St-Elderts Ln,Q,40.691324,-73.867139,4.00,4
86,Z,J20,87,Crescent St,Bk,40.683194,-73.873785,1178.00,1178
87,Z,J21,88,Norwood Av,Bk,40.681410,-73.880039,1174.00,1174
89,Z,J23,90,Van Siclen Av,Bk,40.678024,-73.891688,1198.00,1198
90,Z,J24,91,Alabama Av,Bk,40.676992,-73.898654,1198.00,1198
91,Z,J27,92,Broadway Junction,Bk,40.679498,-73.904512,405.00,405
92,Z,J28,93,Chauncey St,Bk,40.682893,-73.910456,369.00,369
94,Z,J30,95,Gates Av,Bk,40.689630,-73.922270,397.00,397
96,Z,M11,97,Myrtle Av,Bk,40.697207,-73.935657,287.00,287
100,Z,M16,101,Marcy Av,Bk,40.708359,-73.957757,529.00,529
101,Z,M18,102,Delancey St-Essex St,M,40.718315,-73.987437,18.00,18
102,Z,M19,103,Bowery,M,40.720280,-73.993915,18.00,18
103,Z,M20,104,Canal St,M,40.718092,-73.999892,41.00,41
104,Z,M21,105,Chambers St,M,40.713243,-74.003401,29.01,29
105,Z,M22,106,Fulton St,M,40.710374,-74.007582,15.01,15
106,Z,M23,107,Broad St,M,40.706476,-74.011056,7.00,7
278,Z,G05,278,Jamaica Center-Parsons/Archer,Q,40.702147,-73.801109,246.00,246
279,Z,G06,279,Sutphin Blvd-Archer Av-JFK Airport,Q,40.700486,-73.807969,208.00,208

In [16]:
stations_expanded.value_counts('Daytime Routes')

Daytime Routes
2      49
F      45
R      45
5      45
A      44
C      40
1      38
6      38
B      37
D      36
M      36
3      34
J      30
Q      29
4      28
N      28
L      24
W      23
7      22
E      22
G      21
SIR    21
Z      21
S      11
Name: count, dtype: int64

In [14]:
len(stations_expanded['Daytime Routes'].unique())

24